#Jenkins_task5
BOX_IMAGE = "sbeliakou/centos"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "192.168.10.20"
    subconfig.vm.provider "virtualbox" do |vb|
         vb.memory = "2048"
         vb.name = "master"
     end
   subconfig.vm.provision 'shell', path: "jen.sh"
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "slave#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "slave#{i}"
      subconfig.vm.network :private_network, ip: "192.168.10.#{i + 20}"
    config.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.name = "slave#{i}"
      end
     subconfig.vm.provision 'shell', path: "slave.sh"
    end
  end
end
