BOX_IMAGE = "sbeliakou/centos"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
   (1..NODE_COUNT).each do |i|
    config.vm.define "NGINXJ#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "NGINXJ#{i}"
      subconfig.vm.network :private_network, ip: "192.168.21.#{i + 120}"
      subconfig.vm.provision 'shell', path: "Script#{i}.sh"
      subconfig.vm.provider "virtualbox" do |vb|
	vb.memory = "4096"
	vb.name = "NGINXJ#{i}"
	end
    end
  end
end
